# Generated by Django 6.0 on 2025-12-07 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_skill_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sociallink',
            name='url',
            field=models.CharField(max_length=100),
        ),
    ]
